off_20B810:     dc.w unk_20B812-*       ; DATA XREF: sub_20B6C0+50↑o
unk_20B812:     dc.b $10                ; DATA XREF: ROM:off_20B810↑o
                dc.b $C0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $C0
                dc.b $C0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $C0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $C0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $20
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $C0
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $20
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $C0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $20
                dc.b $20
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $C0
                dc.b $20
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $E0
                dc.b $20
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b   0
                dc.b $20
                dc.b  $F
                dc.b   0
                dc.b   0
                dc.b $20
                dc.b   0